### ISSUE TITLE
Unable to signout

### ISSUE THREAD

**Issue by rrubio** [sarfarazansari/ng4-social-login#1]
Hi Guys,

I manage to login ok, however, when trying to logout i get the following error:

Using the following to signout: 

`  signOut(): void {
    this.authService.signOut();
  }
`

`core.es5.js:1020 ERROR Error: Uncaught (in promise): Login provider not found
    at resolvePromise (zone.js:783)
    at zone.js:709
    at ng4-social-login.umd.js:88
    at new ZoneAwarePromise (zone.js:847)
    at AuthService.webpackJsonp.../../../../ng4-social-login/ng4-social-login.umd.js.AuthService.signOut (ng4-social-login.umd.js:75)`

**Comment by vinayak114** [comment]
hi ,

I am also facing same problem for gmail
I am able to login but after logout i am redirecting to login page but it is not actually signing out from gmail account.

 The following method i am using to signout as mentioned in docs:
signOut(): void { this.authService.signOut(); }

The same following error i am getting,

core.es5.js:1020 ERROR Error: Uncaught (in promise): Login provider not found
    at resolvePromise (zone.js:783)
    at zone.js:709
    at ng4-social-login.umd.js:88
    at new ZoneAwarePromise (zone.js:847)
    at AuthService.webpackJsonp.../../../../ng4-social-login/ng4-social-login.umd.js.AuthService.signOut (ng4-social-login.umd.js:75)
    at HomeComponent.webpackJsonp.../../../../../src/app/home/home.component.ts.HomeComponent.gmailLogOut (home.component.ts:49)
    at Object.eval [as handleEvent] (HomeComponent.html:44)
    at handleEvent (core.es5.js:11997)
    at callWithDebugContext (core.es5.js:13458)
    at Object.debugHandleEvent [as handleEvent] (core.es5.js:13046)

**Comment by sarfarazansari** [comment]
@rrubio , @vinayak114  do you guys still facing the issue. please update the plugin to 1.3.5

**Comment by vinayak114** [comment]
No bro its not working after updating plug in to 1.3.5 its giving same error message

**Comment by sarfarazansari** [comment]
@vinayak114 could you please share your snippet. Am unable to understand why is not working. cause same thing is working fine in my case.

**Comment by vinayak114** [comment]
Hi sarfarazansari,
please find below link of my code snippet.
 https://drive.google.com/file/d/1WdguSD6El5YQ9Ypnpjqnqljl81qcEjT-/view?usp=sharing

The problem is I m able to login but when i click logout,
on first click there is no action rather on second click it is logging out.
Its logging out because i have navigated to login page using router and giving below error in console

core.es5.js:1020 ERROR Error: Uncaught (in promise): Login provider not found
    at resolvePromise (zone.js:824)
    at zone.js:746
    at ng4-social-login.umd.js:88
    at new ZoneAwarePromise (zone.js:890)
    at AuthService.webpackJsonp.../../../../ng4-social-login/ng4-social-login.umd.js.AuthService.signOut (ng4-social-login.umd.js:75)
    at HomeComponent.webpackJsonp.../../../../../src/app/home/home.component.ts.HomeComponent.signOut (home.component.ts:34)
    at Object.eval [as handleEvent] (HomeComponent.html:8)
    at handleEvent (core.es5.js:11998)
    at callWithDebugContext (core.es5.js:13467)
    at Object.debugHandleEvent [as handleEvent] 

Thanks in Advance

**Comment by sarfarazansari** [comment]
@vinayak114  `And one more thing if you open gmail in another tab you see the it is still logged in its not signed out from gmail when u click logout.`
Answer: The logout service works like you logout from application not from Google Logout.
